variables:
    ImageBaseName: dfc-docker-hosted-agent


resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.11.2
    endpoint: 'GitHub (ESFA)'

trigger: 
  branches:
    include: 
    - master
  paths: 
    include:
    - Resources/Dockerfiles

pr:
  branches:
    include: 
    - master
  paths: 
    include:
    - Resources/Dockerfiles

stages:
- stage: Build
  variables:
    - group: dfc-shared-all
    - group: dfc-shared-lab

  jobs:
  - template: JobTemplates/BuildContainer.yml
    parameters:
      DevSitContainerRegistryAdminUser: $(DevContainerRegistryAdminUser)
      DevSitContainerRegistryPassword: $(DevContainerRegistryPassword)
      DockerfileContext: 'Resources/DockerFiles'
      DockerfileName: 'Dockerfile'
      ImageBaseName: ${{ variables.ImageBaseName }}
      #TO DO: decide how to tag and publish image builds from branches
      ImageTag: $(Build.BuildNumber)

- stage: DeployDEVStage
  displayName: Deploy DEV stage
  dependsOn: Build
  condition:  and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  variables:
      - group: dfc-shared-all
      - group: KeyVault - dfc-lab-shared-kv
      - group: dfc-shared-lab
      - template: VariableTemplates\DevEnvironmentVariables.yml
      - template: VariableTemplates\SharedEnvironmentVariables.yml
  jobs:
  - template: JobTemplates/Deploy.yml
    parameters:
      AksResourceGroup: $(sharedResourceGroup)
      AzureSubscriptionEndpoint: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      Environment: DEV_SHARED
      ImageBaseName: ${{ variables.ImageBaseName }}
      KeyVaultName: $(sharedKeyVaultName)
      KubernetesCluster: $(sharedAksCluster)
      AzurePatToken:  $(AzureDevOpsAgentPatToken)

