variables:
    ImageBaseName: NCS.Docker.Agent


resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.11.2
    endpoint: 'GitHub (ESFA)'

trigger: 
  branches:
    include: 
    - master
  paths: 
    include:
    - Resources/Dockerfiles

pr:
  branches:
    include: 
    - master
  paths: 
    include:
    - Resources/Dockerfiles

stages:
- stage: Build
  variables:
    - group: dfc-shared-all
    - group: dfc-shared-dev

  jobs:
  - template: JobTemplates/BuildContainer.yml
    parameters:
      DevSitContainerRegistryAdminUser: $(DevContainerRegistryAdminUser)
      DevSitContainerRegistryPassword: $(DevContainerRegistryPassword)
      DockerfileContext: 'Resources/DockerFiles'
      DockerfileName: 'Dockerfile'
      ImageBaseName: ${{ variables.ImageBaseName }}
      #TO DO: decide how to tag and publish image builds from branches
      ImageTag: $(Build.BuildNumber)
